version: '3'

services:
  deploy-web:
    image: deploy-web
    pull_policy: never
    restart: always
    container_name: deploy-web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deploy-web.rule=Host(`web-deploy.thiagosol.com`)"
      - "traefik.http.routers.deploy-web.entrypoints=https"
      - "traefik.http.routers.deploy-web.tls=true"
      - "traefik.http.services.deploy-web.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - external-sol-apis
      - logging-network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=deploy-web,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 50M

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
